#!/bin/bash
set -Eeuo pipefail

# Train the reference-compatible HoVer-Net fast architecture on GlySAC using
# three merged foreground classes. Source, data, checkpoints, and outputs are
# mounted by run.sh, so this command can be changed without rebuilding.

cd /app

DATASET="glysac"
RUN_NAME="${RUN_NAME:-hovernet_fast_glysac_3class}"
EPOCHS="${EPOCHS:-100}"
FREEZE_ENCODER_EPOCHS="${FREEZE_ENCODER_EPOCHS:-50}"
TRAIN_PATCHES_PER_IMAGE="${TRAIN_PATCHES_PER_IMAGE:-8}"
FOREGROUND_PROBABILITY="${FOREGROUND_PROBABILITY:-0.75}"
VISUALIZATIONS="${VISUALIZATIONS:-8}"
FROZEN_BATCH_SIZE="${FROZEN_BATCH_SIZE:-2}"
BATCH_SIZE="${BATCH_SIZE:-1}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-2}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-4}"
FROZEN_ACCUMULATION_STEPS="${FROZEN_ACCUMULATION_STEPS:-8}"
ACCUMULATION_STEPS="${ACCUMULATION_STEPS:-4}"
EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-0}"
PRETRAINED_CHECKPOINT="${PRETRAINED_CHECKPOINT:-outputs/pretrained/imagenet_resnet50_preact.tar}"
CHECKPOINT_DIR="outputs/models/${DATASET}/${RUN_NAME}"
BEST_CHECKPOINT="${CHECKPOINT_DIR}/best.pt"
LAST_CHECKPOINT="${CHECKPOINT_DIR}/last.pt"

[[ -f "${PRETRAINED_CHECKPOINT}" ]] || {
    echo "ERROR: missing ImageNet Preact-ResNet50 weights: ${PRETRAINED_CHECKPOINT}" >&2
    exit 1
}

echo "============================================================"
echo "HoVer-Net fast — GlySAC three-class experiment"
echo "Dataset:      ${DATASET}"
echo "Run:          ${RUN_NAME}"
echo "Classes:      0 background"
echo "              1 miscellaneous <- raw 1,2,9,10"
echo "              2 lymphocyte    <- raw 4,5,6,7"
echo "              3 epithelial    <- raw 3,8"
echo "Architecture: Preact-ResNet50 + NP/HV/type decoders (256 -> 164)"
echo "Initialization: ${PRETRAINED_CHECKPOINT}"
echo "Schedule:     ${FREEZE_ENCODER_EPOCHS} frozen + $((EPOCHS - FREEZE_ENCODER_EPOCHS)) unfrozen epochs"
echo "Frozen batch: ${FROZEN_BATCH_SIZE}x${FROZEN_ACCUMULATION_STEPS} accumulation"
echo "Full batch:   ${BATCH_SIZE}x${ACCUMULATION_STEPS} accumulation"
echo "Sampling:     ${TRAIN_PATCHES_PER_IMAGE} patches/image, ${FOREGROUND_PROBABILITY} class-aware probability"
echo "Results:      outputs/results/${DATASET}/${RUN_NAME}/"
echo "============================================================"

# Rebuild the canonical files so this run always uses the mapping above, even
# if data/processed/glysac was generated by an older checkout.
python3 src/run.py prepare \
    --dataset "${DATASET}" \
    --data-dir data \
    --overwrite

TRAIN_ARGS=()
if [[ -f "${LAST_CHECKPOINT}" ]]; then
    echo "Found ${LAST_CHECKPOINT}; resuming the interrupted run."
    TRAIN_ARGS+=(--resume)
fi

python3 src/run.py train \
    --dataset "${DATASET}" \
    --data-dir data \
    --output-dir outputs \
    --run-name "${RUN_NAME}" \
    --architecture hovernet_fast \
    --pretrained-checkpoint "${PRETRAINED_CHECKPOINT}" \
    --epochs "${EPOCHS}" \
    --freeze-encoder-epochs "${FREEZE_ENCODER_EPOCHS}" \
    --frozen-batch-size "${FROZEN_BATCH_SIZE}" \
    --batch-size "${BATCH_SIZE}" \
    --val-batch-size "${VAL_BATCH_SIZE}" \
    --frozen-gradient-accumulation-steps "${FROZEN_ACCUMULATION_STEPS}" \
    --gradient-accumulation-steps "${ACCUMULATION_STEPS}" \
    --train-patches-per-image "${TRAIN_PATCHES_PER_IMAGE}" \
    --foreground-probability "${FOREGROUND_PROBABILITY}" \
    --early-stopping-patience "${EARLY_STOPPING_PATIENCE}" \
    --patch-size 256 \
    "${TRAIN_ARGS[@]}"

[[ -f "${BEST_CHECKPOINT}" ]] || {
    echo "ERROR: training completed without creating ${BEST_CHECKPOINT}" >&2
    exit 1
}

python3 src/run.py evaluate \
    --dataset "${DATASET}" \
    --checkpoint "${BEST_CHECKPOINT}" \
    --data-dir data \
    --output-dir outputs \
    --run-name "${RUN_NAME}" \
    --architecture hovernet_fast \
    --patch-size 256 \
    --tile-output-size 164 \
    --batch-size "${EVAL_BATCH_SIZE}" \
    --visualizations "${VISUALIZATIONS}"
